In [1]:
import pandas as pd

# Show all rows and columns (no truncation)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 0)
pd.set_option("display.max_colwidth", None)

In [2]:
import pandas as pd

# Load NSE equity symbols
url = "https://public.fyers.in/sym_details/NSE_CM.csv"
df = pd.read_csv(url)

# Display first few
print(df.head())
print(df.shape)

       10100000001     GOLDSTAR POWER LIMITED  0  11250  0.05  INE405Y01021  \
0    1010000000100  AMARA RAJA ENERGY MOB LTD  0      1  0.05  INE885A01032
1   10100000001000          SDL MH 6.56% 2032  5    100  0.01  IN2220200306
2   10100000001001    SEC RED NCD 9.40% SR. V  2      1  0.01  INE721A07NX5
3   10100000001004          SDL AP 6.79% 2034  5    100  0.01  IN1020200466
4  101000000010046        GOI LOAN 7.57% 2033  6      1  0.01  IN0020190065

   0915-1530|1815-1915:  2025-10-17 Unnamed: 8   NSE:GOLDSTAR-SM  10  10.1  \
0  0915-1530|1815-1915:  2025-10-17        NaN      NSE:ARE&M-EQ  10    10
1  0915-1530|1815-1915:  2025-10-17        NaN    NSE:656MH32-SG  10    10
2  0915-1530|1815-1915:  2025-10-17        NaN    NSE:94SFL28-YL  10    10
3  0915-1530|1815-1915:  2025-10-17        NaN    NSE:679AP34-SG  10    10
4  0915-1530|1815-1915:  2025-10-17        NaN  NSE:757GS2033-GS  10    10

       1   GOLDSTAR    1.1  -1.0  XX    10100000001.1  None  0.1  0.0
0    100      ARE&M    100  -1.0  XX    1010000000100   NaN    1  3.2
1   1000    656MH32   1000  -1.0  XX   10100000001000   NaN    0  0.0
2   1001    94SFL28   1001  -1.0  XX   10100000001001   NaN    0  0.0
3   1004    679AP34   1004  -1.0  XX   10100000001004   NaN    0  0.0
4  10046  757GS2033  10046  -1.0  XX  101000000010046   NaN    0  0.0
(8710, 21)

In [3]:
len(df.iloc[:,1].unique())

8196

In [4]:
import pandas as pd

# Load NSE symbols
url = "https://public.fyers.in/sym_details/NSE_CM.csv"
df = pd.read_csv(url)

# Assuming FYERS symbol is in column 9
df.columns = [f"col{i}" for i in range(df.shape[1])]  # temporary column names
symbols = df["col9"].dropna()  # get FYERS symbols

# -------------------------------
# 1️⃣ Count of unique types (after last '-')
types = symbols.str.split('-').str[-1]
type_counts = types.value_counts()
print("Counts of symbol types (descending):")
print(type_counts)

Counts of symbol types (descending):
col9
SG       3732
EQ       2300
N0        617
SM        427
MF        204
BE        154
GS        147
INDEX     120
N1        108
TB         88
ST         86
GB         56
BZ         40
N2         36
N3         30
N6         26
N5         23
N7         23
NA         22
NC         22
ND         21
N4         20
N9         19
IV         19
NB         18
NE         17
N8         17
NF         14
NG         13
NH         11
NJ         10
NM         10
NL         10
NK         10
E1          9
NN          9
NI          9
NO          8
NS          7
NR          7
NP          6
NQ          6
NX          5
NW          5
NV          5
RR          5
NT          5
NU          5
NY          4
NZ          4
Z9          3
Y1          3
IT          3
SZ          3
YS          3
Y2          3
Y0          3
YL          2
Z8          2
Z6          2
Z7          2
SF          2
W1          2
ZL          2
P1          2
ZN          2
ZM          2
ZC          2
ZT          2
D1          2
YA          2
YC          2
Y9          2
Y3          2
YP          2
YR          2
YI          2
Z5          2
ZI          2
ZF          2
YB          2
YQ          2
YT          2
YZ          2
YW          2
M1          1
BC          1
AZ          1
AY          1
AW          1
BA          1
AV          1
AU          1
AH          1
AJ          1
AK          1
AL          1
AM          1
AN          1
AI          1
ZZ          1
ZX          1
ZW          1
ZV          1
ZU          1
ZY          1
AX          1
BX          1
BU          1
Y8          1
Y7          1
Y6          1
Y5          1
Y4          1
BV          1
BR          1
BS          1
YK          1
YM          1
YN          1
YO          1
YD          1
YG          1
YH          1
YJ          1
BW          1
Z2          1
Z1          1
YU          1
YV          1
YX          1
YY          1
Z0          1
ZE          1
ZD          1
ZB          1
ZA          1
Z4          1
Z3          1
ZG          1
ZH          1
ZR          1
ZQ          1
ZP          1
ZO          1
ZK          1
ZJ          1
ZS          1
X1          1
Name: count, dtype: int64

In [5]:
import pandas as pd

# Load NSE symbols
url = "https://public.fyers.in/sym_details/NSE_CM.csv"
df = pd.read_csv(url)

# Assign temporary column names for clarity
df.columns = [f"col{i}" for i in range(df.shape[1])]
df_subset = df.iloc[:, [1, 9]]  # company name and FYERS symbol
df_subset.columns = ["Company", "FyersSymbol"]

# Keep only EQ, INDEX, and MF symbols
df_filtered = df_subset[df_subset["FyersSymbol"].str.endswith(("EQ", "INDEX", "MF"))]

# Reset index
df_filtered = df_filtered.reset_index(drop=True)

# Save to CSV
# df_filtered.to_csv("symbols_filtered.csv", index=False)
print(f"Filtered symbols saved: {df_filtered.shape[0]} entries")

Filtered symbols saved: 2624 entries